apiVersion: broker.amq.io/v2alpha1
kind: ActiveMQArtemis
metadata:
  name: broker-amq-mqtt
  namespace: iotdemo
spec:
  acceptors:
  - expose: true
    name: all
    port: 61616
  console:
    expose: true
  deploymentPlan:
    image: registry.redhat.io/amq7/amq-broker:7.5
    journalType: nio
    messageMigration: false
    persistenceEnabled: false
    requireLogin: false
    size: 1
