apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: iot-consumer
  name: iot-consumer
  namespace: iotdemo
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: iot-consumer:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: components/iot-consumer
    git:
      uri: https://github.com/sa-mw-dach/manuela-dev.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:10
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - imageChange: null
    type: ImageChange
status:
  lastVersion: 0
