apiVersion: v1
data:
  config.json: |-
    {
        "websocketHost": "http://iot-consumer-iotdemo.apps.ly-demo.west.aws.redhat-demo.com",
        "websocketPath": "/api/service-web/socket",
        "SERVER_TIMEOUT": 20000
    }
kind: ConfigMap
metadata:
  name: iot-frontend-cfg
  namespace: iotdemo
