apiVersion: v1
data:
  ANOMALY_DETECTION_URL: http://anomaly-detection-anomaly-detection:8000
  MQTT_BROKER: ws://broker-amq-mqtt-all-0-svc:61616
  MQTT_PASSWORD: iotuser
  MQTT_USER: iotuser
  PORT: "3000"
  SOCKET_PATH: /api/service-web/socket
  TEMPERATURE_ALERT_ENABLED: "false"
  TEMPERATURE_THRESHOLD: "70.0"
  TOPIC_GPS: iot-sensor/sw/gps
  TOPIC_LIGHT: iot-sensor/sw/light
  TOPIC_TEMPERATURE: iot-sensor/sw/temperature
  TOPIC_VIBRATION: iot-sensor/sw/vibration
  VIBRATION_ALERT_ENABLED: "false"
  VIBRATION_ANOMALY_ENABLED: "false"
kind: ConfigMap
metadata:
  name: iot-consumer-cfg
  namespace: iotdemo
