apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: quay-enterprise

bases:
- ../../../../../manifests/app/operators/quay-operator/base

resources:
- quay-namespace.yaml
- quay-og.yaml