apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: airlineinputtopic
  labels:
    strimzi.io/cluster: my-cluster
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "0"
spec:
  partitions: 3
  replicas: 3
