apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-producer-hw
spec:
  # once every two minutes
  schedule: '*/1 * * * *'
  # once a week at 00:00 on Sunday
  #schedule: '*/30 * * * *'
  jobTemplate:
    spec:
      parallelism: 5
      completions: 4
      template:
        metadata:
        spec:
          containers:
          - name: hello-world-producer
            env:
              - name: BOOTSTRAP_SERVERS
                value: my-cluster-kafka-bootstrap.myproject-dev:9092
              - name: TOPIC
                value: my-topic
              - name: DELAY_MS
                value: "0"
              - name: LOG_LEVEL
                value: "INFO"
              - name: MESSAGE_COUNT
                value: "10000"
              - name: PRODUCER_ACKS
                value: "all"
