apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-app
  labels:
    app: iot-demo
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-demo
  template:
    metadata:
      labels:
        app: iot-demo
        name: consumer-app
    spec:
      containers:
        - name: consumer-app
          image: strimzilab/consumer-app:latest
          env:
            - name: BOOTSTRAP_SERVERS
              value: "my-cluster-kafka-bootstrap.myproject:9092"
            - name: CONSUMER_GROUPID
              value: "consumer-app"
            - name: CONSUMER_TOPIC
              value: "iot-temperature-max"
            - name: CONSUMER_AUTO_OFFSET_RESET
              value: "earliest"
          #resources:
            #requests:
              #memory: "250Mi"
              #cpu: "100m"
            #limits:
              #memory: "350Mi"
              #cpu: "250m"
