apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: grafana

bases:
- ../../../../instances/overlays/backend/letsencrypt-service

resources:
- acme-namespace.yaml