apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-datasource
spec:
  datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus.myproject-dev:9090