apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-datasource
spec:
  datasources:
    - name: ${DS_PROMETHEUS}
      type: prometheus
      access: proxy
      url: http://prometheus.myproject-dev:9090
      isDefault: true
      editable: true
      jsonData:
        tlsSkipVerify: true
        timeInterval: "5s"