apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-producer-hw
spec:
  # once every two minutes
  #schedule: '*/1 * * * *'
  # once a week at 00:00 on Sunday
  #schedule: '*/30 * * * *'
  # once per hour
  schedule: '0 * * * *'
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      parallelism: 1
      completions: 5
      template:
        metadata:
          annotations:
            argocd.argoproj.io/hook: PostSync
            argocd.argoproj.io/hook-delete-policy: HookSucceeded
        spec:
          containers:
          - name: hello-world-producer
            image: strimzi/hello-world-producer:latest
            env:
              - name: BOOTSTRAP_SERVERS
                value: my-cluster-kafka-bootstrap.myproject-dev:9092
              - name: TOPIC
                value: my-topic
              - name: DELAY_MS
                value: "0"
              - name: LOG_LEVEL
                value: "INFO"
              - name: MESSAGE_COUNT
                value: "1000000"
              - name: PRODUCER_ACKS
                value: "all"
              - name: ADDITIONAL_CONFIG
                value: |
                  retries=100
          restartPolicy: OnFailure
      backoffLimit: 5
