apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-consumer-rv
  name: hello-world-consumer-rv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-consumer-rv
  template:
    metadata:
      labels:
        app: hello-world-consumer-rv
    spec:
      containers:
      - name: hello-world-consumer
        image: strimzi/hello-world-consumer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap.myproject-dev:9092
          - name: TOPIC
            value: my-topic-reversed
          - name: GROUP_ID
            value: my-hello-world-consumer
          - name: LOG_LEVEL
            value: "INFO"
          - name: MESSAGE_COUNT
            value: "10000000"
          - name: ADDITIONAL_CONFIG
            value: |
              max.poll.records=100