apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: myproject-dev

bases:
- ../../../../../manifests/app/operators/strimzi-kafka-operator/base
- ../../../../../manifests/app/operators/prometheus-operator/base

resources:
- myproject-operatorgroup.yaml
- myproject-namespace.yaml

patchesStrategicMerge:
- patches/myproject-dev-clusterrolebinding.yaml