apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: iotdemo-app

bases:
- ../../../../instances/overlays/frontend/iotdemo-app/dashboard
- ../../../../instances/overlays/frontend/iotdemo-app/device-sensor
- ../../../../instances/overlays/frontend/iotdemo-app/stream
- ../../../../instances/overlays/frontend/iotdemo-app/kafka-topics

resources:
- namespace.yaml

patchesStrategicMerge:
- patches/device-replicas.yaml
- patches/consumer-bootstrap.yaml
- patches/device-bootstrap.yaml
- patches/stream-bootstrap.yaml