apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: codeready

bases:
- ../../../../templates/app/backend/codeready-workspaces-service/base