apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: iot-temperature
  labels:
    app: iot-demo
    strimzi.io/cluster: my-cluster
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  partitions: 1
  replicas: 3
