kind: Pod
apiVersion: v1
metadata:
  name: kafka-producer
  labels:
    run: kafka-producer
spec:
  containers:
    - resources: {}
      stdin: true
      terminationMessagePath: /dev/termination-log
      stdinOnce: true
      name: kafka-producer
      securityContext:
        capabilities:
          drop:
            - MKNOD
      imagePullPolicy: IfNotPresent
      image: 'confluentinc/cp-kafka:5.0.0'
      command:
              - sh
              - -c
              - "kafka-producer-perf-test --topic my-topic1 --num-records 2500000 --record-size 5 --throughput 10 --producer-props acks=1 buffer.memory=67108864 compression.type=lz4 batch.size=20000 linger.ms=100 retries=0 bootstrap.servers=my-cluster-kafka-bootstrap.myproject:9092"
