apiVersion: v1
items:
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineRun
  metadata:
    labels:
      tekton.dev/pipeline: build-only-pipeline
    name: build-only-pipeline-run-v1
  spec:
    pipelineRef:
      name: build-only-pipeline
    podTemplate: {}
    resources:
    - name: api-repo
      resourceRef:
        name: api-repo
    - name: api-image
      resourceRef:
        name: api-image
    - name: ui-repo
      resourceRef:
        name: ui-repo
    - name: ui-image
      resourceRef:
        name: ui-image
    serviceAccountName: pipeline
    timeout: 1h0m0s
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
