apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: vote-cicd-triggertemplate
spec:
  params:
  - name: eventid
    description: eventid payload of listener
  - name: namespace
    description: The namespace to create the resources
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: build-and-deploy-run-
      labels:
        tekton.dev/pipeline: build-and-deploy
    spec:
      pipelineRef:
        name: build-and-deploy
      podTemplate: {}
      resources:
      - name: ui-repo
        resourceRef:
          name: ui-repo
      - name: ui-image
        resourceRef:
          name: ui-image
      - name: api-repo
        resourceRef:
          name: api-repo
      - name: api-image
        resourceRef:
          name: api-image
      serviceAccountName: pipeline
      timeout: 1h0m0s
