apiVersion: apps/v1
kind: Deployment
metadata:
  name: airline-prediction-stream
spec:
  selector:
    matchLabels:
      app: airline-prediction-stream
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: airline-prediction-stream
    spec:
      containers:
      - name: airline-prediction-stream
        image: ably77/airlineprediction-stream:v1
