apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: codeready-workspaces
  namespace: codeready
  annotations:
    #argocd.argoproj.io/hook: Sync
    #argocd.argoproj.io/hook-delete-policy: HookSucceeded
    #argocd.argoproj.io/sync-wave: "2"
spec:
  channel: latest
  installPlanApproval: Automatic
  name: codeready-workspaces
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: crwoperator.v2.2.0
