# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- iotdemo-app.yaml
- kafka-loadtest-app.yaml
- manuela-line-dashboard-app.yaml
- manuela-machine-sensor-app.yaml
- bookinfo-app.yaml