apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: manuela-quickstart-messaging

bases:
- ../../../../instances/overlays/operators/amq-broker-operator