apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: grafana

bases:
- ../../../../templates/app/backend/letsencrypt-service/base

resources:
- acme-namespace.yaml