apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: openshift-operators

bases:
- ../../../../../manifests/cluster-config/node-feature-discovery-operator/base