# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- issuer-letsencrypt-live.yaml
- letsencrypt-route.yaml


