apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-broker
  namespace: iotdemo
spec:
  channel: current
  installPlanApproval: Automatic
  name: amq-broker
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: amq-broker-operator.v0.15.0
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: iotdemo-
  generation: 1
  name: iotdemo-9sjbt
  namespace: iotdemo
spec:
  targetNamespaces:
  - iotdemo
