apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: myproject-dev

bases:
- ../../../../../manifests/app/operators/prometheus-operator/base