apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: airlineprediction-stream-dev

bases:
- ../../../../manifests/app/frontend/airline-prediction-stream/base

resources:
- namespace.yaml