apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-producer-hw
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 10
  parallelism: 1
  completions: 50
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: kafka-producer-hw
    spec:
      containers:
      - name: hello-world-producer
        image: strimzi/hello-world-producer:latest
        imagePullPolicy: IfNotPresent
        #resources:
          #requests:
            #memory: "500Mi"
            #cpu: "250m"
          #limits:
            #memory: "500Mi"
            #cpu: "250m"
        env:
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap.myproject-dev:9092
          - name: TOPIC
            value: my-topic
          - name: DELAY_MS
            value: "0"
          - name: LOG_LEVEL
            value: "INFO"
          - name: MESSAGE_COUNT
            value: "10000000"
          - name: PRODUCER_ACKS
            value: "all"
          - name: ADDITIONAL_CONFIG
            value: |
              retries=100
      restartPolicy: OnFailure
  backoffLimit: 5
