apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: myproject-dev

bases:
- ../../../../instances/overlays/operators/strimzi-kafka-operator
- ../../../../instances/overlays/operators/prometheus-operator