apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: my-topic1
  labels:
    strimzi.io/cluster: my-cluster
    strimzi.io/cluster: mm2-target-kafka
spec:
  partitions: 3
  replicas: 3
