apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/connects-to: broker-amq-mqtt-ss,iot-frontend
  labels:
    app: iot-consumer
    app.kubernetes.io/part-of: ManuELA
  name: iot-consumer
  namespace: iotdemo
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: iot-consumer
    deploymentconfig: iot-consumer
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: iot-consumer
        deploymentconfig: iot-consumer
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: iot-consumer-cfg
        image: iot-consumer:latest
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: iot-consumer
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - iot-consumer
      from:
        kind: ImageStreamTag
        name: iot-consumer:latest
    type: ImageChange
