apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: iotdemo-app

bases:
- ../../../../manifests/app/frontend/iotdemo-app/dashboard/base
- ../../../../manifests/app/frontend/iotdemo-app/device-sensor/base
- ../../../../manifests/app/frontend/iotdemo-app/stream/base
- ../../../../manifests/app/frontend/iotdemo-app/kafka-topics/base

resources:
- namespace.yaml

patchesStrategicMerge:
- patches/device-replicas.yaml
- patches/consumer-bootstrap.yaml
- patches/device-bootstrap.yaml
- patches/stream-bootstrap.yaml