apiVersion: apps/v1
kind: Deployment
metadata:
  name: machine-sensor-1
spec:
  template:
    spec:
      containers:
      - name: machine-sensor
        image: quay.io/manuela/iot-software-sensor:0.3.1-16
        imagePullPolicy: Always