apiVersion: operator.tekton.dev/v1alpha1
kind: Config
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "0"
spec:
  targetNamespace: openshift-pipelines
