apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: iotdemo-app

bases:
- ../../../../../templates/app/frontend/iotdemo-app/base

resources:
- namespace.yaml

patchesStrategicMerge:
- patches/device-replicas.yaml
- patches/consumer-bootstrap.yml
- patches/device-bootstrap.yml
- patches/stream-bootstrap.yml
