apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: grafana

bases:
- ../../../../templates/app/backend/integreatly-grafana-service/base

patchesStrategicMerge:
- patches/prometheus-ds.yaml