apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: codeready

bases:
- ../../../../templates/app/operators/codeready-workspaces-operator/base

resources:
- codeready-namespace.yaml