apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: manuela-quickstart-messaging

bases:
- ../../../../templates/app/operators/amq-broker-operator/base

resources:
- manuela-namespace.yaml